# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
    - linux
    - osx
julia:
    - nightly
sudo: false
notifications:
    email: false
after_success:
    - julia -e 'include(Pkg.dir("Docile", "test", "coverage.jl"))'
