environment:
  matrix:
    - JULIAVERSION: "win32"
    - JULIAVERSION: "win64"

install:
  - ps: (new-object net.webclient).DownloadFile($("http://status.julialang.org/download/"+$env:JULIAVERSION), "C:\projects\julia-binary.exe")
  - C:\projects\julia-binary.exe /S /D=C:\projects\julia

build_script:
  - IF EXIST .git\shallow (git fetch --unshallow)
  - C:\projects\julia\bin\julia -e "versioninfo(); Pkg.init(); Pkg.clone(pwd(), \"Docile\"); Pkg.add(\"Lexicon\")"

test_script:
  - C:\projects\julia\bin\julia test\runtests.jl
